spring:
  datasource:
    master:
      hikari:
        driver-class-name: ${SPRING_DATASOURCE_DRIVER}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        jdbc-url: ${SPRING_DATASOURCE_MASTER_URL}
        maximum-pool-size: 20
    slave:
      hikari:
        driver-class-name: ${SPRING_DATASOURCE_DRIVER}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        jdbc-url: ${SPRING_DATASOURCE_SLAVE_URL}
        maximum-pool-size: 20